# Generated by Django 2.2 on 2019-04-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_tropic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tropic',
        ),
    ]
